### ISSUE TITLE
may be have some error

### ISSUE THREAD

**Issue by lllidan-yuandian** [KOD-Chen/YOLOv2-Tensorflow#3]
https://github.com/KOD-Chen/YOLOv2-Tensorflow/blob/de8c542a3c79cf40f4a0979a4758499535ea089a/Loss.py#L72

May be you have forgot the parameter of 'thresh=0.6' when computing the nonobj loss

**Comment by guker** [comment]
I also think this have problems @KOD-Chen

**Comment by Cecilia520** [comment]
how to modify?

**Comment by lllidan-yuandian** [comment]
> how to modify?

        confs = tf.multiply(best_box, _confs)
        valid_confs = tf.greater(iou, const.nonobj_thresh)
        valid_confs = tf.to_float(valid_confs)
        bg_confs = (1 - valid_confs)*(1 - confs)
        conid = const.noobject_scale * bg_confs + const.object_scale * confs
